find_package(PkgConfig REQUIRED)
find_package(Perl REQUIRED)
find_program(BISON_EXECUTABLE bison)
if(NOT BISON_EXECUTABLE)
    message(FATAL_ERROR "bison package not found. Install it to be able to compile owb.")
endif(NOT BISON_EXECUTABLE)
find_program(FLEX_EXECUTABLE flex)
if(NOT FLEX_EXECUTABLE)
    message(FATAL_ERROR "flex package not found. Install it to be able to compile owb.")
endif(NOT FLEX_EXECUTABLE)
find_program(GPERF_EXECUTABLE gperf)
if(NOT GPERF_EXECUTABLE)
    message(FATAL_ERROR "gperf package not found. Install it to be able to compile owb.")
endif(NOT GPERF_EXECUTABLE)


pkg_check_modules(OWB_BASE_DEPS REQUIRED libxml-2.0>=2.6)
