if(USE_NETWORK STREQUAL "CURL")
    pkg_check_modules(CURL REQUIRED libcurl>=7.15)
    set(NETWORK_INCLUDE_DIRS ${CURL_INCLUDE_DIRS})
    set(NETWORK_LIBRARIES ${CURL_LIBRARIES})

    set(USE_NETWORK_CURL TRUE)
    mark_as_advanced(USE_NETWORK_CURL)
endif(USE_NETWORK STREQUAL "CURL")

if(USE_NETWORK STREQUAL "QT")
    pkg_check_modules(QTNETWORK REQUIRED QtNetwork)
    pkg_check_modules(QTCORE REQUIRED QtCore)
    set(NETWORK_INCLUDE_DIRS ${QTNETWORK_INCLUDE_DIRS} ${QTCORE_INCLUDE_DIRS})
    set(NETWORK_LIBRARIES ${QTNETWORK_LIBRARIES} ${QTCORE_LIBRARIES})

    set(USE_NETWORK_QT TRUE)
    mark_as_advanced(USE_NETWORK_QT)
endif(USE_NETWORK STREQUAL "QT")

if(USE_NETWORK STREQUAL "SOUP")
    pkg_check_modules(SOUP REQUIRED libsoup-2.4>=2.25)
    set(NETWORK_INCLUDE_DIRS ${SOUP_INCLUDE_DIRS})
    set(NETWORK_LIBRARIES ${SOUP_LIBRARIES})

    set(USE_NETWORK_SOUP TRUE)
    mark_as_advanced(USE_NETWORK_SOUP)
endif(USE_NETWORK STREQUAL "SOUP")
